---
title: "testfigs"
output: pdf_document
#output: word_document
author: "Andy South"
date: "`r Sys.Date()`"
---

#testing getting figures side-by-side


```{r,echo=FALSE,results='hide'}
  library(resistance)
  #library(ggplot2)
```

why are the figs being pushed down the page ....


```{r, eval=TRUE, echo=FALSE, fig.height=3.7, fig.width=3.7, fig.show='hold', fig.align='left', fig.cap="A. All control inputs equal at 0.5, B. Effectiveness of insecticide1 increased from 0.5 to 0.9"}
#fig.cap seems necessary to keep figs side by side

#plot margins
oldpar <- par(mar=c(4, 4, 2, 0)) #b,l,t,r default c(5, 4, 4, 2)

runcurtis_f2( max_gen=500,  P_1 = 0.01 , P_2 = 0.01 , h.RS1_A0 = 0.5 , h.RS2_0B = 0.5 , exposure = 0.5 , phi.SS1_A0 = 0.5 , phi.SS2_0B = 0.5 , rr_restoration_ins1 = 0.5 , rr_restoration_ins2 = 0.5 , addCombinedStrategy = FALSE, strategyLabels = c('seq','','adapt','mix2'), addLegend=FALSE, main='A.' )

#plot margins
par(mar=c(4, 0, 2, 0)) #b,l,t,r default c(5, 4, 4, 2)

runcurtis_f2( max_gen=500,  P_1 = 0.01 , P_2 = 0.01 , h.RS1_A0 = 0.5 , h.RS2_0B = 0.5 , exposure = 0.5 , phi.SS1_A0 = 0.9 , phi.SS2_0B = 0.5 , rr_restoration_ins1 = 0.5 , rr_restoration_ins2 = 0.5 , addCombinedStrategy = FALSE, strategyLabels = c('seq','','adapt','mix2'), ylab="", main='B.' )

par(oldpar)

```

